    $rg = "tua"
    $loc = "west europe"
    $nic01 = "eth0-web01-mgmt"
    $nic02 = "eth1-web01-prod"
    $nic03 = "eth2-Internet"
    $vnet = Get-AzureRmVirtualNetwork -Name ‘Prod’ -ResourceGroupName ‘TuA’
    $sub01id = (Get-AzureRmVirtualNetworkSubnetConfig -Name ‘Websubnet’ -VirtualNetwork $vnet).Id
    $sub02id = (Get-AzureRmVirtualNetworkSubnetConfig -Name ‘AppSubnet’ -VirtualNetwork $vnet).Id
    $sub03id = (Get-AzureRmVirtualNetworkSubnetConfig -Name ‘DBSubnet’ -VirtualNetwork $vnet).Id
    $ip1 = '10.0.21.6'
    $ip2 = '10.0.22.7'
    $ip3 = '10.0.23.5'
    $nic1 = New-AzureRmNetworkInterface -Name $nic01 -ResourceGroupName $rg -Location $loc -SubnetId $sub01id -PrivateIpAddress $ip1
    $nic2 = New-AzureRmNetworkInterface -Name $nic02 -ResourceGroupName $rg -Location $loc -SubnetId $sub02id -PrivateIpAddress $ip2
    $nic3 = New-AzureRmNetworkInterface -Name $nic03 -ResourceGroupName $rg -Location $loc -SubnetId $sub03id -PrivateIpAddress $ip3
    $vmsize = "Standard_DS2_v2" 
    $vmname = "web03" 
    $vm = New-AzureRmVMConfig -VMName $vmname -VMSize $vmsize 
    $VM = Add-AzureRmVMNetworkInterface -VM $VM -Id $nic1.Id -Primary
    $VM = Add-AzureRmVMNetworkInterface -VM $VM -Id $nic2.Id
    $VM = Add-AzureRmVMNetworkInterface -VM $VM -Id $nic3.Id
    $osDiskName = "web03" 
    $osDiskVhdUri = "https://tuastorage.blob.core.windows.net/vhds2/shapp-tua-web01.vhd" 
    $vm = Set-AzureRmVMOSDisk -VM $vm -VhdUri $osDiskVhdUri -name $osDiskName -CreateOption attach -linux
    New-AzureRmVM -ResourceGroupName $rg -Location $loc -VM $vm